import type { KnowledgeCard } from './elastic.client.js';

// GENERATED by `npm run seed:verify`. Every card here was produced from a
// real Docker sandbox run (see src/services/seeds/*.ts for the source
// fixtures and src/scripts/verify-seeds.ts for how). Do not hand-edit —
// re-run `npm run seed:verify` instead.
export const SEED_KNOWLEDGE_CARDS: KnowledgeCard[] = [
  {
    "id": "fix_python_print_statement_syntax",
    "problem": "Python 2 print statement syntax raises a SyntaxError under Python 3",
    "errorType": "SyntaxError",
    "stacktrace": "File \"/workspace/main.py\", line 1\n    print \"hello world\"\n    ^^^^^^^^^^^^^^^^^^^\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,1 +1,1 @@\n-print \"hello world\"\n+print(\"hello world\")",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:44.693Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 98,
      "stdout": "hello world\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:44.693Z"
    }
  },
  {
    "id": "fix_python_except_comma_syntax",
    "problem": "Python 2 \"except Exception, e:\" syntax raises a SyntaxError under Python 3",
    "errorType": "SyntaxError",
    "stacktrace": "File \"/workspace/main.py\", line 3\n    except ValueError, e:\n           ^^^^^^^^^^^^^\nSyntaxError: multiple exception types must be parenthesized",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n try:\n     raise ValueError(\"bad value\")\n-except ValueError, e:\n+except ValueError as e:\n     print(e)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:44.879Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 87,
      "stdout": "bad value\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:44.879Z"
    }
  },
  {
    "id": "fix_python_collections_abc_import",
    "problem": "ImportError: cannot import name 'Mapping' from 'collections' on Python 3.10+",
    "errorType": "ImportError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 1, in <module>\n    from collections import Mapping\nImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,3 +1,3 @@\n-from collections import Mapping\n+from collections.abc import Mapping\n \n print(issubclass(dict, Mapping))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:45.094Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "True\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:45.094Z"
    }
  },
  {
    "id": "fix_python_str_int_concat",
    "problem": "TypeError when concatenating a string literal with an int without str() conversion",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(\"Total: \" + count)\n          ~~~~~~~~~~^~~~~~~\nTypeError: can only concatenate str (not \"int\") to str",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n count = 5\n-print(\"Total: \" + count)\n+print(\"Total: \" + str(count))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:45.295Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 97,
      "stdout": "Total: 5\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:45.295Z"
    }
  },
  {
    "id": "fix_python_zero_division_unguarded",
    "problem": "Unguarded division by a value that can be zero raises ZeroDivisionError",
    "errorType": "ZeroDivisionError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(average(10, 0))\n          ^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in average\n    return total / count\n           ~~~~~~^~~~~~~\nZeroDivisionError: division by zero",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,6 @@\n def average(total, count):\n+    if count == 0:\n+        return 0\n     return total / count\n \n print(average(10, 0))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:45.521Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 111,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:45.521Z"
    }
  },
  {
    "id": "fix_python_keyerror_dict_access",
    "problem": "Direct dict subscript access on a possibly-missing key raises KeyError",
    "errorType": "KeyError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(config[\"port\"])\n          ~~~~~~^^^^^^^^\nKeyError: 'port'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n config = {\"host\": \"localhost\"}\n-print(config[\"port\"])\n+print(config.get(\"port\", 8080))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:45.735Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 103,
      "stdout": "8080\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:45.735Z"
    }
  },
  {
    "id": "fix_python_index_off_by_one",
    "problem": "Off-by-one indexing with len(lst) instead of len(lst)-1 raises IndexError",
    "errorType": "IndexError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(items[len(items)])\n          ~~~~~^^^^^^^^^^^^\nIndexError: list index out of range",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n items = [10, 20, 30]\n-print(items[len(items)])\n+print(items[len(items) - 1])",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:45.947Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 104,
      "stdout": "30\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:45.947Z"
    }
  },
  {
    "id": "fix_python_missing_return_none_attribute",
    "problem": "Function missing a return statement implicitly returns None, causing AttributeError on the caller side",
    "errorType": "AttributeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 7, in <module>\n    values.append(4)\n    ^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'append'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,8 +1,9 @@\n def build_list(items):\n     result = []\n     for item in items:\n         result.append(item * 2)\n+    return result\n \n values = build_list([1, 2, 3])\n values.append(4)\n print(values)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:46.153Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 105,
      "stdout": "[2, 4, 6, 4]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:46.153Z"
    }
  },
  {
    "id": "fix_python_unbound_local_variable",
    "problem": "Assigning to a module-level variable name inside a function without \"global\" raises UnboundLocalError",
    "errorType": "UnboundLocalError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 7, in <module>\n    print(increment())\n          ^^^^^^^^^^^\n  File \"/workspace/main.py\", line 4, in increment\n    counter = counter + 1\n              ^^^^^^^\nUnboundLocalError: cannot access local variable 'counter' where it is not associated with a value",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,7 +1,8 @@\n counter = 0\n \n def increment():\n+    global counter\n     counter = counter + 1\n     return counter\n \n print(increment())",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:46.349Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 97,
      "stdout": "1\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:46.349Z"
    }
  },
  {
    "id": "fix_python_recursion_missing_base_case",
    "problem": "Recursive function without a base case raises RecursionError",
    "errorType": "RecursionError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(factorial(5))\n          ^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  [Previous line repeated 996 more times]\nRecursionError: maximum recursion depth exceeded",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,6 @@\n def factorial(n):\n+    if n <= 1:\n+        return 1\n     return n * factorial(n - 1)\n \n print(factorial(5))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:46.548Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 95,
      "stdout": "120\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:46.548Z"
    }
  },
  {
    "id": "fix_python_json_decode_empty_string",
    "problem": "Parsing an empty string with json.loads raises JSONDecodeError",
    "errorType": "JSONDecodeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    data = json.loads(raw)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,5 +1,5 @@\n import json\n \n raw = \"\"\n-data = json.loads(raw)\n+data = json.loads(raw) if raw else {}\n print(data)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:46.812Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 139,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:46.812Z"
    }
  },
  {
    "id": "fix_python_file_not_found_unguarded",
    "problem": "Opening a file that does not exist without a fallback raises FileNotFoundError",
    "errorType": "FileNotFoundError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 1, in <module>\n    with open(\"/tmp/hm_missing_config.json\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/hm_missing_config.json'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,8 @@\n-with open(\"/tmp/hm_missing_config.json\") as f:\n+import os\n+\n+path = \"/tmp/hm_missing_config.json\"\n+if not os.path.exists(path):\n+    with open(path, \"w\") as f:\n+        f.write(\"{}\")\n+with open(path) as f:\n     print(f.read())",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:47.013Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 96,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:47.013Z"
    }
  },
  {
    "id": "fix_python_returns_count_not_iterable",
    "problem": "Function returns a count instead of the collection, causing TypeError when the caller iterates over it",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 5, in <module>\n    for item in get_active_items([{\"active\": True}, {\"active\": False}]):\nTypeError: 'int' object is not iterable",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,6 +1,6 @@\n def get_active_items(items):\n     active = [item for item in items if item.get(\"active\")]\n-    return len(active)\n+    return active\n \n for item in get_active_items([{\"active\": True}, {\"active\": False}]):\n     print(item)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:47.214Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 104,
      "stdout": "{'active': True}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:47.214Z"
    }
  },
  {
    "id": "fix_python_dict_changed_size_during_iteration",
    "problem": "Deleting dict keys while iterating directly over the dict raises RuntimeError",
    "errorType": "RuntimeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    for key in data:\nRuntimeError: dictionary changed size during iteration",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,5 +1,5 @@\n data = {\"a\": 1, \"b\": -1, \"c\": 2, \"d\": -2}\n-for key in data:\n+for key in list(data.keys()):\n     if data[key] < 0:\n         del data[key]\n print(data)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:47.415Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 100,
      "stdout": "{'a': 1, 'c': 2}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:47.415Z"
    }
  },
  {
    "id": "fix_python_name_error_conditional_assignment",
    "problem": "A variable only assigned inside an untaken branch raises NameError when referenced afterward",
    "errorType": "NameError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(message)\n          ^^^^^^^\nNameError: name 'message' is not defined",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,5 @@\n condition = False\n+message = \"default\"\n if condition:\n     message = \"hello\"\n print(message)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:47.623Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "default\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:47.623Z"
    }
  },
  {
    "id": "fix_python_missing_required_argument",
    "problem": "Calling a function without a required positional argument raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(greet(\"World\"))\n          ^^^^^^^^^^^^^^\nTypeError: greet() missing 1 required positional argument: 'greeting'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n-def greet(name, greeting):\n+def greet(name, greeting=\"Hello\"):\n     return f\"{greeting}, {name}!\"\n \n print(greet(\"World\"))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:47.831Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 100,
      "stdout": "Hello, World!\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:47.831Z"
    }
  },
  {
    "id": "fix_python_int_conversion_unvalidated",
    "problem": "Converting a non-numeric string with int() without validation raises ValueError",
    "errorType": "ValueError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    number = int(value)\n             ^^^^^^^^^^\nValueError: invalid literal for int() with base 10: 'abc'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,3 +1,6 @@\n value = \"abc\"\n-number = int(value)\n+try:\n+    number = int(value)\n+except ValueError:\n+    number = 0\n print(number)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:48.041Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 105,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:48.041Z"
    }
  },
  {
    "id": "fix_python_sort_none_comparison",
    "problem": "Sorting a list containing None alongside numbers raises TypeError in Python 3",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 3, in <module>\n    values.sort()\nTypeError: '<' not supported between instances of 'NoneType' and 'int'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n records = [{\"score\": 5}, {\"score\": None}, {\"score\": 3}]\n-values = [r.get(\"score\") for r in records]\n+values = [r.get(\"score\", 0) or 0 for r in records]\n values.sort()\n print(values)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:48.251Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 99,
      "stdout": "[0, 3, 5]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:48.251Z"
    }
  },
  {
    "id": "fix_python_unhandled_stop_iteration",
    "problem": "Calling next() on an exhausted iterator without a default raises StopIteration",
    "errorType": "StopIteration",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 8, in <module>\n    print(first_positive([-1, -2, -3]))\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 4, in first_positive\n    value = next(it)\n            ^^^^^^^^\nStopIteration",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,8 +1,10 @@\n def first_positive(numbers):\n     it = iter(numbers)\n     while True:\n-        value = next(it)\n+        value = next(it, None)\n+        if value is None:\n+            return None\n         if value > 0:\n             return value\n \n print(first_positive([-1, -2, -3]))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:48.448Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 97,
      "stdout": "None\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:48.448Z"
    }
  },
  {
    "id": "fix_python_sort_mixed_types",
    "problem": "Sorting a list with mixed str/int elements raises TypeError in Python 3",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(sorted(values))\n          ^^^^^^^^^^^^^^\nTypeError: '<' not supported between instances of 'str' and 'int'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n values = [3, \"a\", 2]\n-print(sorted(values))\n+print(sorted(values, key=str))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:48.658Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "[2, 3, 'a']\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T14:47:48.658Z"
    }
  },
  {
    "id": "fix_node_require_in_esm",
    "problem": "ReferenceError: require is not defined in ES module scope",
    "errorType": "ReferenceError",
    "stacktrace": "file:///tmp/main.mjs:1\nconst path = require('node:path');\n             ^\n\nReferenceError: require is not defined in ES module scope, you can use import instead\n    at file:///tmp/main.mjs:1:14\n    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-const path = require('node:path');\n+import path from 'node:path';\n console.log(path.basename('/tmp/main.mjs'));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:48.882Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "main.mjs\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:48.882Z"
    }
  },
  {
    "id": "fix_node_import_in_commonjs",
    "problem": "ES module \"import\" statement used in a file Node treats as CommonJS raises a SyntaxError",
    "errorType": "SyntaxError",
    "stacktrace": "(node:4) Warning: To load an ES module, set \"type\": \"module\" in the package.json or use the .mjs extension.\n(Use `node --trace-warnings ...` to show where the warning was created)\n/tmp/main.cjs:1\nimport { readFileSync } from 'node:fs';\n^^^^^^\n\nSyntaxError: Cannot use import statement outside a module\n    at wrapSafe (node:internal/modules/cjs/loader:1464:18)\n    at Module._compile (node:internal/modules/cjs/loader:1495:20)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-import { readFileSync } from 'node:fs';\n+const { readFileSync } = require('node:fs');\n console.log(typeof readFileSync);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:49.101Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 113,
      "stdout": "function\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:49.101Z"
    }
  },
  {
    "id": "fix_node_json_parse_empty_string",
    "problem": "JSON.parse on an empty string raises SyntaxError: Unexpected end of JSON input",
    "errorType": "SyntaxError",
    "stacktrace": "<anonymous_script>:1\n\n\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:2:19)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const raw = \"\";\n-const data = JSON.parse(raw);\n+const data = raw ? JSON.parse(raw) : {};\n console.log(data);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:49.318Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 113,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:49.318Z"
    }
  },
  {
    "id": "fix_node_undefined_property_chain",
    "problem": "Reading a nested property through an undefined intermediate raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\n  return user.address.city;\n                      ^\n\nTypeError: Cannot read properties of undefined (reading 'city')\n    at getUserCity (/workspace/main.js:2:23)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function getUserCity(user) {\n-  return user.address.city;\n+  return user.address?.city ?? 'unknown';\n }\n console.log(getUserCity({ name: 'Ada' }));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:49.537Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "unknown\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:49.537Z"
    }
  },
  {
    "id": "fix_node_reduce_empty_array_no_initial",
    "problem": "Array.prototype.reduce on an empty array with no initial value raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:1\nconst total = [].reduce((acc, val) => acc + val);\n                 ^\n\nTypeError: Reduce of empty array with no initial value\n    at Array.reduce (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:1:18)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-const total = [].reduce((acc, val) => acc + val);\n+const total = [].reduce((acc, val) => acc + val, 0);\n console.log(total);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:49.760Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:49.760Z"
    }
  },
  {
    "id": "fix_node_circular_json_stringify",
    "problem": "JSON.stringify on an object with a circular reference raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:3\nconsole.log(JSON.stringify(obj));\n                 ^\n\nTypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Object'\n    --- property 'self' closes the circle\n    at JSON.stringify (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:3:18)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const obj = { name: 'root' };\n obj.self = obj;\n-console.log(JSON.stringify(obj));\n+console.log(JSON.stringify(obj, (key, value) => (key === 'self' ? undefined : value)));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:49.982Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 111,
      "stdout": "{\"name\":\"root\"}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:49.982Z"
    }
  },
  {
    "id": "fix_node_map_on_null",
    "problem": "Calling .map() on a null value instead of an array raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\n  return items.map((x) => x * 2);\n               ^\n\nTypeError: Cannot read properties of null (reading 'map')\n    at double (/workspace/main.js:2:16)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function double(items) {\n-  return items.map((x) => x * 2);\n+  return (items ?? []).map((x) => x * 2);\n }\n console.log(double(null));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:50.205Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 116,
      "stdout": "[]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:50.205Z"
    }
  },
  {
    "id": "fix_node_unhandled_promise_rejection",
    "problem": "Calling an async function without awaiting or catching its rejection crashes the process",
    "errorType": "UnhandledPromiseRejection",
    "stacktrace": "/workspace/main.js:2\n  throw new Error('config missing');\n        ^\n\nError: config missing\n    at loadConfig (/workspace/main.js:2:9)\n    at Object.<anonymous> (/workspace/main.js:5:1)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,6 +1,13 @@\n async function loadConfig() {\n   throw new Error('config missing');\n }\n \n-loadConfig();\n-console.log('this line runs before the crash is reported');\n+async function main() {\n+  try {\n+    await loadConfig();\n+  } catch (error) {\n+    console.log('handled:', error.message);\n+  }\n+}\n+\n+main();",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:50.437Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 117,
      "stdout": "handled: config missing\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:50.437Z"
    }
  },
  {
    "id": "fix_node_max_call_stack_recursion",
    "problem": "Recursive function without a base case raises RangeError: Maximum call stack size exceeded",
    "errorType": "RangeError",
    "stacktrace": "/workspace/main.js:2\n  return n * factorial(n - 1);\n  ^\n\nRangeError: Maximum call stack size exceeded\n    at factorial (/workspace/main.js:2:3)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,5 @@\n function factorial(n) {\n+  if (n <= 1) return 1;\n   return n * factorial(n - 1);\n }\n console.log(factorial(5));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:50.672Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 120,
      "stdout": "120\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:50.672Z"
    }
  },
  {
    "id": "fix_node_property_not_a_function",
    "problem": "Calling .push() on a plain object instead of an array raises TypeError: is not a function",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nqueue.push(1);\n      ^\n\nTypeError: queue.push is not a function\n    at Object.<anonymous> (/workspace/main.js:2:7)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const queue = { items: [] };\n-queue.push(1);\n+queue.items.push(1);\n console.log(queue.items);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:50.880Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 105,
      "stdout": "[ 1 ]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:50.880Z"
    }
  },
  {
    "id": "fix_node_cannot_find_module",
    "problem": "require() of a relative path that does not exist raises \"Cannot find module\"",
    "errorType": "Error",
    "stacktrace": "node:internal/modules/cjs/loader:1210\n  throw err;\n  ^\n\nError: Cannot find module './missing-utils.js'\nRequire stack:\n- /workspace/main.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)\n    at Module._load (node:internal/modules/cjs/loader:1038:27)\n    at Module.require (node:internal/modules/cjs/loader:1289:19)\n    at require (node:internal/modules/helpers:182:18)\n    at Object.<anonymous> (/workspace/main.js:1:15)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [ '/workspace/main.js' ]\n}\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,5 @@\n-const utils = require('./missing-utils.js');\n+const fs = require('node:fs');\n+const path = '/tmp/utils.js';\n+fs.writeFileSync(path, 'module.exports = { greet: (name) => `hello, ${name}` };');\n+const utils = require(path);\n console.log(utils.greet('world'));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:51.092Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 104,
      "stdout": "hello, world\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:51.092Z"
    }
  },
  {
    "id": "fix_node_const_reassignment",
    "problem": "Reassigning a const-declared variable raises TypeError: Assignment to constant variable",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nretries = retries - 1;\n        ^\n\nTypeError: Assignment to constant variable.\n    at Object.<anonymous> (/workspace/main.js:2:9)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n-const retries = 3;\n+let retries = 3;\n retries = retries - 1;\n console.log(retries);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:51.298Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 103,
      "stdout": "2\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:51.298Z"
    }
  },
  {
    "id": "fix_node_block_scope_reference_error",
    "problem": "Referencing a let-declared variable outside the block it was declared in raises ReferenceError",
    "errorType": "ReferenceError",
    "stacktrace": "/workspace/main.js:4\nconsole.log(message);\n            ^\n\nReferenceError: message is not defined\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,5 @@\n+let message;\n if (true) {\n-  let message = 'hello';\n+  message = 'hello';\n }\n console.log(message);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:51.516Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 110,
      "stdout": "hello\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:51.516Z"
    }
  },
  {
    "id": "fix_node_symbol_to_string_conversion",
    "problem": "Implicitly converting a Symbol to a string via template literal raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nconsole.log(`ID: ${id}`);\n                   ^\n\nTypeError: Cannot convert a Symbol value to a string\n    at Object.<anonymous> (/workspace/main.js:2:20)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n const id = Symbol('user-id');\n-console.log(`ID: ${id}`);\n+console.log(`ID: ${String(id)}`);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:51.734Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 108,
      "stdout": "ID: Symbol(user-id)\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:51.734Z"
    }
  },
  {
    "id": "fix_node_invalid_array_length",
    "problem": "Constructing an Array with a negative length raises RangeError: Invalid array length",
    "errorType": "RangeError",
    "stacktrace": "/workspace/main.js:2\n  return new Array(size);\n         ^\n\nRangeError: Invalid array length\n    at createBuffer (/workspace/main.js:2:10)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function createBuffer(size) {\n-  return new Array(size);\n+  return new Array(Math.max(0, size));\n }\n console.log(createBuffer(-1).length);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:51.952Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 106,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T14:47:51.952Z"
    }
  },
  {
    "id": "fix_docker_unknown_instruction_typo",
    "problem": "A typo'd Dockerfile instruction (\"RUNN\") fails the build with an unknown-instruction error",
    "errorType": "DockerBuildError",
    "stacktrace": "time=\"2026-07-25T20:17:51+05:30\" level=error msg=\"+(UNHANDLED LOGLEVEL) &imagebuilder.Step{Env:[]string{\\\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\"}, Command:\\\"runn\\\", Args:[]string{\\\"\\\"}, Flags:[]string{}, Attrs:map[string]bool(nil), Message:\\\"RUNN \\\", Heredocs:[]parser.Heredoc(nil), Original:\\\"RUNN echo \\\\\\\"hello\\\\\\\"\\\"}\"\nError: building at STEP \"RUNN \": Build error: Unknown instruction: \"RUNN\" &imagebuilder.Step{Env:[]string{\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"}, Command:\"runn\", Args:[]string{\"\"}, Flags:[]string{}, Attrs:map[string]bool(nil), Message:\"RUNN \", Heredocs:[]parser.Heredoc(nil), Original:\"RUNN echo \\\"hello\\\"\"}",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-RUNN echo \"hello\"\n+RUN echo \"hello\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:47:52.439Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 347,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo \"hello\"\nhello\nCOMMIT hm-seed-verify-1e29a14806ee\n--> af09cba2b175\nSuccessfully tagged localhost/hm-seed-verify-1e29a14806ee:latest\naf09cba2b175e89bafd39af4f106ec5654a757836f0197988c754ccd60b88742\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:47:52.439Z"
    }
  },
  {
    "id": "fix_docker_copy_from_wrong_stage_name",
    "problem": "COPY --from referencing a build stage name that was never defined fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: COPY --from=wrongstage: no stage or image found with that name",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,5 +1,5 @@\n FROM alpine:3.19 AS builder\n RUN echo \"build\" > /out.txt\n \n FROM alpine:3.19\n-COPY --from=wrongstage /out.txt /out.txt\n+COPY --from=builder /out.txt /out.txt",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:01.703Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 6930,
      "stdout": "[1/2] STEP 1/2: FROM alpine:3.19 AS builder\n[1/2] STEP 2/2: RUN echo \"build\" > /out.txt\n--> f05037b552b2\n[2/2] STEP 1/2: FROM alpine:3.19\n[2/2] STEP 2/2: COPY --from=builder /out.txt /out.txt\n[2/2] COMMIT hm-seed-verify-f80df5dc9482\n--> 2a8258ccc153\nSuccessfully tagged localhost/hm-seed-verify-f80df5dc9482:latest\n2a8258ccc153afb8b5ec511c9e9b2335e3fc982c8c19108b995093a2647c3691\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:01.703Z"
    }
  },
  {
    "id": "fix_docker_copy_missing_context_file",
    "problem": "COPY referencing a file that does not exist in the build context fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"COPY nonexistent-file.txt /app/nonexistent-file.txt\": checking on sources under \"/var/tmp/buildah-context-961483183/overlay/669943460/merge\": copier: stat: \"/nonexistent-file.txt\": no such file or directory",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-COPY nonexistent-file.txt /app/nonexistent-file.txt\n+RUN mkdir -p /app && echo \"generated at build time\" > /app/nonexistent-file.txt",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:02.126Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 336,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN mkdir -p /app && echo \"generated at build time\" > /app/nonexistent-file.txt\nCOMMIT hm-seed-verify-61d870780513\n--> 50d69a6b5275\nSuccessfully tagged localhost/hm-seed-verify-61d870780513:latest\n50d69a6b5275fea895233a65f4f286a569c4c246933ac4703cd3ef8772a486c3\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:02.126Z"
    }
  },
  {
    "id": "fix_docker_env_missing_value",
    "problem": "An ENV instruction with only a key and no value fails to parse",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: parsing main Dockerfile: /tmp/hm-docker-fixture-i5uqSp/Dockerfile: ENV must have two arguments",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n-ENV APP_PORT\n+ENV APP_PORT=8080\n CMD [\"sh\", \"-c\", \"echo listening on $APP_PORT\"]",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:02.282Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 89,
      "stdout": "STEP 1/3: FROM alpine:3.19\nSTEP 2/3: ENV APP_PORT=8080\n--> f3f1384a5b23\nSTEP 3/3: CMD [\"sh\", \"-c\", \"echo listening on $APP_PORT\"]\nCOMMIT hm-seed-verify-6ac6ead8bdbd\n--> 5341d249d912\nSuccessfully tagged localhost/hm-seed-verify-6ac6ead8bdbd:latest\n5341d249d912e8daf6d6b817dea5ccc522f1cfac2b7a7a4f8337d69abe9cb325\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:02.282Z"
    }
  },
  {
    "id": "fix_docker_missing_from_first_instruction",
    "problem": "A Dockerfile whose first instruction is not FROM fails to build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: reading multiple stages: stage 1 requires a FROM instruction (\"\")",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n-RUN echo \"no from\"\n FROM alpine:3.19\n+RUN echo \"no from\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:02.688Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 343,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo \"no from\"\nno from\nCOMMIT hm-seed-verify-60a11f168076\n--> f10192362054\nSuccessfully tagged localhost/hm-seed-verify-60a11f168076:latest\nf1019236205441bb607b0cf3469242a44a15640a88a61b279cb1545577757537\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:02.688Z"
    }
  },
  {
    "id": "fix_docker_healthcheck_invalid_interval",
    "problem": "A HEALTHCHECK with a non-duration --interval value fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"HEALTHCHECK --interval=notanumber CMD echo ok\": time: invalid duration \"notanumber\"",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-HEALTHCHECK --interval=notanumber CMD echo ok\n+HEALTHCHECK --interval=30s CMD echo ok",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:02.820Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 59,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: HEALTHCHECK --interval=30s CMD echo ok\nCOMMIT hm-seed-verify-2fdfd54a00dc\n--> 09f92fe637d4\nSuccessfully tagged localhost/hm-seed-verify-2fdfd54a00dc:latest\n09f92fe637d44efae447a61b432426a67455b688f5fb07503e1936b81ae9a428\n",
      "stderr": "time=\"2026-07-25T20:18:02+05:30\" level=warning msg=\"HEALTHCHECK is not supported for OCI image format and will be ignored. Must use `docker` format\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:02.820Z"
    }
  },
  {
    "id": "fix_docker_copy_from_invalid_stage_index",
    "problem": "COPY --from referencing a numeric build-stage index that does not exist fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: COPY --from=5: no stage or image found with that name",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n FROM alpine:3.19\n-COPY --from=5 /etc/hostname /tmp/hostname\n+COPY --from=0 /etc/hostname /tmp/hostname",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:10.031Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 4902,
      "stdout": "[1/2] STEP 1/1: FROM alpine:3.19\n--> 83b2b6703a62\n[2/2] STEP 1/2: FROM alpine:3.19\n[2/2] STEP 2/2: COPY --from=0 /etc/hostname /tmp/hostname\n[2/2] COMMIT hm-seed-verify-094362a25584\n--> af94246c6974\nSuccessfully tagged localhost/hm-seed-verify-094362a25584:latest\naf94246c6974d79863e79f019dc330feddba299904b8fd25464527d2fea4acf7\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:10.031Z"
    }
  },
  {
    "id": "fix_docker_workdir_missing_argument",
    "problem": "A WORKDIR instruction with no path argument fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"WORKDIR \": WORKDIR requires exactly one argument",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-WORKDIR\n+WORKDIR /app",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:10.158Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 59,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: WORKDIR /app\nCOMMIT hm-seed-verify-93bafee2888e\n--> af2589ae96ba\nSuccessfully tagged localhost/hm-seed-verify-93bafee2888e:latest\naf2589ae96bae90775a0b8127fb60ec2fa60a30002c05eaff04ea19f6cf3d18e\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:10.158Z"
    }
  },
  {
    "id": "fix_docker_user_nonexistent",
    "problem": "A USER instruction referencing a user that does not exist in the image fails subsequent RUN steps",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"RUN echo hi\": determining run uid: user: unknown user error looking up user \"nonexistentuser\"",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n-USER nonexistentuser\n+USER root\n RUN echo hi",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:10.859Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 445,
      "stdout": "STEP 1/3: FROM alpine:3.19\nSTEP 2/3: USER root\n--> 5ba85cc54c0d\nSTEP 3/3: RUN echo hi\nhi\nCOMMIT hm-seed-verify-ecac87665d51\n--> a49a8ea32f6c\nSuccessfully tagged localhost/hm-seed-verify-ecac87665d51:latest\na49a8ea32f6c796c942f6bbd67db65f3a3f4074e9064803b67be150e57b99b2f\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:10.859Z"
    }
  },
  {
    "id": "fix_docker_stopsignal_invalid",
    "problem": "A STOPSIGNAL instruction with an invalid signal name fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"STOPSIGNAL NOTASIGNAL\": Invalid signal: NOTASIGNAL",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-STOPSIGNAL NOTASIGNAL\n+STOPSIGNAL SIGTERM",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:10.990Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 59,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: STOPSIGNAL SIGTERM\nCOMMIT hm-seed-verify-3989eea7560c\n--> 4133864cff5d\nSuccessfully tagged localhost/hm-seed-verify-3989eea7560c:latest\n4133864cff5d2160b9ebf3d75780adf78b545e0a7eb229bce4f0f3f80274df6b\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:10.990Z"
    }
  },
  {
    "id": "fix_docker_arg_undeclared_before_from",
    "problem": "Referencing an ARG in FROM without declaring it beforehand leaves FROM with no image and fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: determining starting point for build: no FROM statement found",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,3 @@\n+ARG BASE_IMAGE=alpine:3.19\n FROM ${BASE_IMAGE}\n RUN echo hi",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:11.372Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 319,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo hi\nhi\nCOMMIT hm-seed-verify-46385a44e95a\n--> c5657efe63c1\nSuccessfully tagged localhost/hm-seed-verify-46385a44e95a:latest\nc5657efe63c139c76f6b2934a29ab326f5c12584c19c8fbfaceee893ad7d4339\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:11.372Z"
    }
  },
  {
    "id": "fix_docker_shell_invalid_form",
    "problem": "A SHELL instruction not written as a JSON array fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"SHELL /bin/sh -c\": SHELL requires the arguments to be in JSON form",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-SHELL /bin/sh -c\n+SHELL [\"/bin/sh\", \"-c\"]",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:11.500Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 60,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: SHELL [\"/bin/sh\", \"-c\"]\nCOMMIT hm-seed-verify-2ed14600dc84\n--> 7ec703a8d61f\nSuccessfully tagged localhost/hm-seed-verify-2ed14600dc84:latest\n7ec703a8d61f91c167f779c0348e05bb3ff8452c9a68b89142f127951b63f1f5\n",
      "stderr": "time=\"2026-07-25T20:18:11+05:30\" level=warning msg=\"SHELL is not persisted in the OCI image format, [/bin/sh -c] will be used for RUN subsequent instructions to build this image but will not be present in saved image which may affect any images that use this as a base. Must use `docker` format to persist in saved image\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:11.500Z"
    }
  },
  {
    "id": "fix_docker_onbuild_forbidden_trigger",
    "problem": "ONBUILD wrapping a FROM instruction fails the build, since FROM is not allowed as an ONBUILD trigger",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"ONBUILD from alpine:3.19\": FROM isn't allowed as an ONBUILD trigger",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-ONBUILD FROM alpine:3.19\n+ONBUILD RUN echo \"building downstream image\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:11.628Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 60,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: ONBUILD RUN echo \"building downstream image\"\nCOMMIT hm-seed-verify-5252e9dae456\n--> a9387cd71775\nSuccessfully tagged localhost/hm-seed-verify-5252e9dae456:latest\na9387cd71775fd8e295b8b484d70524aec653eac1741805617d60efe1292b249\n",
      "stderr": "time=\"2026-07-25T20:18:11+05:30\" level=warning msg=\"ONBUILD is not supported for OCI image format, RUN echo \\\"building downstream image\\\" will be ignored. Must use `docker` format\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:11.628Z"
    }
  },
  {
    "id": "fix_docker_compose_bad_indentation",
    "problem": "A docker-compose.yml with a stray extra indentation level fails YAML parsing",
    "errorType": "ComposeConfigError",
    "stacktrace": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0mCRITICAL:podman_compose:Compose file contains an error:\nmapping values are not allowed here\n  in \"/tmp/hm-docker-fixture-sBmcnT/compose.yml\", line 4, column 11\nError: executing /usr/bin/podman-compose -f /tmp/hm-docker-fixture-sBmcnT/compose.yml config: exit status 1",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/docker-compose.yml\n+++ b/docker-compose.yml\n@@ -1,5 +1,5 @@\n services:\n   web:\n     image: alpine:3.19\n-     ports:\n+    ports:\n       - \"8080:80\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:11.823Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 98,
      "stdout": "services:\n  web:\n    image: alpine:3.19\n    ports:\n    - 8080:80\n\n",
      "stderr": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0m"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:11.823Z"
    }
  },
  {
    "id": "fix_docker_compose_tab_character",
    "problem": "A docker-compose.yml containing a tab character for indentation fails YAML parsing",
    "errorType": "ComposeConfigError",
    "stacktrace": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0mCRITICAL:podman_compose:Compose file contains an error:\nwhile scanning for the next token\nfound character '\\t' that cannot start any token\n  in \"/tmp/hm-docker-fixture-OEEZHq/compose.yml\", line 3, column 1\nError: executing /usr/bin/podman-compose -f /tmp/hm-docker-fixture-OEEZHq/compose.yml config: exit status 1",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/docker-compose.yml\n+++ b/docker-compose.yml\n@@ -1,3 +1,3 @@\n services:\n   web:\n-\timage: alpine:3.19\n+    image: alpine:3.19",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T14:48:12.018Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 99,
      "stdout": "services:\n  web:\n    image: alpine:3.19\n\n",
      "stderr": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0m"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T14:48:12.018Z"
    }
  }
];
