import type { KnowledgeCard } from './elastic.client.js';

// GENERATED by `npm run seed:verify`. Every card here was produced from a
// real Docker sandbox run (see src/services/seeds/*.ts for the source
// fixtures and src/scripts/verify-seeds.ts for how). Do not hand-edit —
// re-run `npm run seed:verify` instead.
export const SEED_KNOWLEDGE_CARDS: KnowledgeCard[] = [
  {
    "id": "fix_python_print_statement_syntax",
    "problem": "Python 2 print statement syntax raises a SyntaxError under Python 3",
    "errorType": "SyntaxError",
    "stacktrace": "File \"/workspace/main.py\", line 1\n    print \"hello world\"\n    ^^^^^^^^^^^^^^^^^^^\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,1 +1,1 @@\n-print \"hello world\"\n+print(\"hello world\")",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:07.073Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 130,
      "stdout": "hello world\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:07.073Z"
    }
  },
  {
    "id": "fix_python_except_comma_syntax",
    "problem": "Python 2 \"except Exception, e:\" syntax raises a SyntaxError under Python 3",
    "errorType": "SyntaxError",
    "stacktrace": "File \"/workspace/main.py\", line 3\n    except ValueError, e:\n           ^^^^^^^^^^^^^\nSyntaxError: multiple exception types must be parenthesized",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n try:\n     raise ValueError(\"bad value\")\n-except ValueError, e:\n+except ValueError as e:\n     print(e)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:07.339Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 116,
      "stdout": "bad value\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:07.339Z"
    }
  },
  {
    "id": "fix_python_collections_abc_import",
    "problem": "ImportError: cannot import name 'Mapping' from 'collections' on Python 3.10+",
    "errorType": "ImportError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 1, in <module>\n    from collections import Mapping\nImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,3 +1,3 @@\n-from collections import Mapping\n+from collections.abc import Mapping\n \n print(issubclass(dict, Mapping))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:07.589Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 113,
      "stdout": "True\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:07.589Z"
    }
  },
  {
    "id": "fix_python_str_int_concat",
    "problem": "TypeError when concatenating a string literal with an int without str() conversion",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(\"Total: \" + count)\n          ~~~~~~~~~~^~~~~~~\nTypeError: can only concatenate str (not \"int\") to str",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n count = 5\n-print(\"Total: \" + count)\n+print(\"Total: \" + str(count))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:07.822Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 118,
      "stdout": "Total: 5\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:07.822Z"
    }
  },
  {
    "id": "fix_python_zero_division_unguarded",
    "problem": "Unguarded division by a value that can be zero raises ZeroDivisionError",
    "errorType": "ZeroDivisionError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(average(10, 0))\n          ^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in average\n    return total / count\n           ~~~~~~^~~~~~~\nZeroDivisionError: division by zero",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,6 @@\n def average(total, count):\n+    if count == 0:\n+        return 0\n     return total / count\n \n print(average(10, 0))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:08.066Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 119,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:08.066Z"
    }
  },
  {
    "id": "fix_python_keyerror_dict_access",
    "problem": "Direct dict subscript access on a possibly-missing key raises KeyError",
    "errorType": "KeyError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(config[\"port\"])\n          ~~~~~~^^^^^^^^\nKeyError: 'port'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n config = {\"host\": \"localhost\"}\n-print(config[\"port\"])\n+print(config.get(\"port\", 8080))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:08.304Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 121,
      "stdout": "8080\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:08.304Z"
    }
  },
  {
    "id": "fix_python_index_off_by_one",
    "problem": "Off-by-one indexing with len(lst) instead of len(lst)-1 raises IndexError",
    "errorType": "IndexError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(items[len(items)])\n          ~~~~~^^^^^^^^^^^^\nIndexError: list index out of range",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n items = [10, 20, 30]\n-print(items[len(items)])\n+print(items[len(items) - 1])",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:08.523Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 110,
      "stdout": "30\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:08.523Z"
    }
  },
  {
    "id": "fix_python_missing_return_none_attribute",
    "problem": "Function missing a return statement implicitly returns None, causing AttributeError on the caller side",
    "errorType": "AttributeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 7, in <module>\n    values.append(4)\n    ^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'append'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,8 +1,9 @@\n def build_list(items):\n     result = []\n     for item in items:\n         result.append(item * 2)\n+    return result\n \n values = build_list([1, 2, 3])\n values.append(4)\n print(values)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:08.751Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 124,
      "stdout": "[2, 4, 6, 4]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:08.751Z"
    }
  },
  {
    "id": "fix_python_unbound_local_variable",
    "problem": "Assigning to a module-level variable name inside a function without \"global\" raises UnboundLocalError",
    "errorType": "UnboundLocalError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 7, in <module>\n    print(increment())\n          ^^^^^^^^^^^\n  File \"/workspace/main.py\", line 4, in increment\n    counter = counter + 1\n              ^^^^^^^\nUnboundLocalError: cannot access local variable 'counter' where it is not associated with a value",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,7 +1,8 @@\n counter = 0\n \n def increment():\n+    global counter\n     counter = counter + 1\n     return counter\n \n print(increment())",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:08.979Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 121,
      "stdout": "1\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:08.979Z"
    }
  },
  {
    "id": "fix_python_recursion_missing_base_case",
    "problem": "Recursive function without a base case raises RecursionError",
    "errorType": "RecursionError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(factorial(5))\n          ^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 2, in factorial\n    return n * factorial(n - 1)\n               ^^^^^^^^^^^^^^^^\n  [Previous line repeated 996 more times]\nRecursionError: maximum recursion depth exceeded",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,6 @@\n def factorial(n):\n+    if n <= 1:\n+        return 1\n     return n * factorial(n - 1)\n \n print(factorial(5))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:09.204Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 119,
      "stdout": "120\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:09.204Z"
    }
  },
  {
    "id": "fix_python_json_decode_empty_string",
    "problem": "Parsing an empty string with json.loads raises JSONDecodeError",
    "errorType": "JSONDecodeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    data = json.loads(raw)\n           ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,5 +1,5 @@\n import json\n \n raw = \"\"\n-data = json.loads(raw)\n+data = json.loads(raw) if raw else {}\n print(data)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:09.489Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 141,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:09.489Z"
    }
  },
  {
    "id": "fix_python_file_not_found_unguarded",
    "problem": "Opening a file that does not exist without a fallback raises FileNotFoundError",
    "errorType": "FileNotFoundError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 1, in <module>\n    with open(\"/tmp/hm_missing_config.json\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/hm_missing_config.json'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,8 @@\n-with open(\"/tmp/hm_missing_config.json\") as f:\n+import os\n+\n+path = \"/tmp/hm_missing_config.json\"\n+if not os.path.exists(path):\n+    with open(path, \"w\") as f:\n+        f.write(\"{}\")\n+with open(path) as f:\n     print(f.read())",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:09.704Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 106,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:09.704Z"
    }
  },
  {
    "id": "fix_python_returns_count_not_iterable",
    "problem": "Function returns a count instead of the collection, causing TypeError when the caller iterates over it",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 5, in <module>\n    for item in get_active_items([{\"active\": True}, {\"active\": False}]):\nTypeError: 'int' object is not iterable",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,6 +1,6 @@\n def get_active_items(items):\n     active = [item for item in items if item.get(\"active\")]\n-    return len(active)\n+    return active\n \n for item in get_active_items([{\"active\": True}, {\"active\": False}]):\n     print(item)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:09.930Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "{'active': True}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:09.930Z"
    }
  },
  {
    "id": "fix_python_dict_changed_size_during_iteration",
    "problem": "Deleting dict keys while iterating directly over the dict raises RuntimeError",
    "errorType": "RuntimeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    for key in data:\nRuntimeError: dictionary changed size during iteration",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,5 +1,5 @@\n data = {\"a\": 1, \"b\": -1, \"c\": 2, \"d\": -2}\n-for key in data:\n+for key in list(data.keys()):\n     if data[key] < 0:\n         del data[key]\n print(data)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:10.163Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "{'a': 1, 'c': 2}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:10.163Z"
    }
  },
  {
    "id": "fix_python_name_error_conditional_assignment",
    "problem": "A variable only assigned inside an untaken branch raises NameError when referenced afterward",
    "errorType": "NameError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(message)\n          ^^^^^^^\nNameError: name 'message' is not defined",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,5 @@\n condition = False\n+message = \"default\"\n if condition:\n     message = \"hello\"\n print(message)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:10.391Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 116,
      "stdout": "default\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:10.391Z"
    }
  },
  {
    "id": "fix_python_missing_required_argument",
    "problem": "Calling a function without a required positional argument raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 4, in <module>\n    print(greet(\"World\"))\n          ^^^^^^^^^^^^^^\nTypeError: greet() missing 1 required positional argument: 'greeting'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n-def greet(name, greeting):\n+def greet(name, greeting=\"Hello\"):\n     return f\"{greeting}, {name}!\"\n \n print(greet(\"World\"))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:10.628Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 126,
      "stdout": "Hello, World!\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:10.628Z"
    }
  },
  {
    "id": "fix_python_int_conversion_unvalidated",
    "problem": "Converting a non-numeric string with int() without validation raises ValueError",
    "errorType": "ValueError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    number = int(value)\n             ^^^^^^^^^^\nValueError: invalid literal for int() with base 10: 'abc'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,3 +1,6 @@\n value = \"abc\"\n-number = int(value)\n+try:\n+    number = int(value)\n+except ValueError:\n+    number = 0\n print(number)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:10.871Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 122,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:10.871Z"
    }
  },
  {
    "id": "fix_python_sort_none_comparison",
    "problem": "Sorting a list containing None alongside numbers raises TypeError in Python 3",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 3, in <module>\n    values.sort()\nTypeError: '<' not supported between instances of 'NoneType' and 'int'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,4 +1,4 @@\n records = [{\"score\": 5}, {\"score\": None}, {\"score\": 3}]\n-values = [r.get(\"score\") for r in records]\n+values = [r.get(\"score\", 0) or 0 for r in records]\n values.sort()\n print(values)",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:11.097Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 113,
      "stdout": "[0, 3, 5]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:11.097Z"
    }
  },
  {
    "id": "fix_python_unhandled_stop_iteration",
    "problem": "Calling next() on an exhausted iterator without a default raises StopIteration",
    "errorType": "StopIteration",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 8, in <module>\n    print(first_positive([-1, -2, -3]))\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspace/main.py\", line 4, in first_positive\n    value = next(it)\n            ^^^^^^^^\nStopIteration",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,8 +1,10 @@\n def first_positive(numbers):\n     it = iter(numbers)\n     while True:\n-        value = next(it)\n+        value = next(it, None)\n+        if value is None:\n+            return None\n         if value > 0:\n             return value\n \n print(first_positive([-1, -2, -3]))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:11.309Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 109,
      "stdout": "None\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:11.309Z"
    }
  },
  {
    "id": "fix_python_sort_mixed_types",
    "problem": "Sorting a list with mixed str/int elements raises TypeError in Python 3",
    "errorType": "TypeError",
    "stacktrace": "Traceback (most recent call last):\n  File \"/workspace/main.py\", line 2, in <module>\n    print(sorted(values))\n          ^^^^^^^^^^^^^^\nTypeError: '<' not supported between instances of 'str' and 'int'",
    "environment": {
      "language": "python",
      "version": "3.11"
    },
    "patch": "===================================================================\n--- a/main.py\n+++ b/main.py\n@@ -1,2 +1,2 @@\n values = [3, \"a\", 2]\n-print(sorted(values))\n+print(sorted(values, key=str))",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:11.512Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 98,
      "stdout": "[2, 3, 'a']\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "python",
      "addedAt": "2026-07-25T15:05:11.512Z"
    }
  },
  {
    "id": "fix_node_require_in_esm",
    "problem": "ReferenceError: require is not defined in ES module scope",
    "errorType": "ReferenceError",
    "stacktrace": "file:///tmp/main.mjs:1\nconst path = require('node:path');\n             ^\n\nReferenceError: require is not defined in ES module scope, you can use import instead\n    at file:///tmp/main.mjs:1:14\n    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-const path = require('node:path');\n+import path from 'node:path';\n console.log(path.basename('/tmp/main.mjs'));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:11.752Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 126,
      "stdout": "main.mjs\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:11.752Z"
    }
  },
  {
    "id": "fix_node_import_in_commonjs",
    "problem": "ES module \"import\" statement used in a file Node treats as CommonJS raises a SyntaxError",
    "errorType": "SyntaxError",
    "stacktrace": "(node:4) Warning: To load an ES module, set \"type\": \"module\" in the package.json or use the .mjs extension.\n(Use `node --trace-warnings ...` to show where the warning was created)\n/tmp/main.cjs:1\nimport { readFileSync } from 'node:fs';\n^^^^^^\n\nSyntaxError: Cannot use import statement outside a module\n    at wrapSafe (node:internal/modules/cjs/loader:1464:18)\n    at Module._compile (node:internal/modules/cjs/loader:1495:20)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-import { readFileSync } from 'node:fs';\n+const { readFileSync } = require('node:fs');\n console.log(typeof readFileSync);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:11.985Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "function\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:11.985Z"
    }
  },
  {
    "id": "fix_node_json_parse_empty_string",
    "problem": "JSON.parse on an empty string raises SyntaxError: Unexpected end of JSON input",
    "errorType": "SyntaxError",
    "stacktrace": "<anonymous_script>:1\n\n\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:2:19)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const raw = \"\";\n-const data = JSON.parse(raw);\n+const data = raw ? JSON.parse(raw) : {};\n console.log(data);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:12.220Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 126,
      "stdout": "{}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:12.220Z"
    }
  },
  {
    "id": "fix_node_undefined_property_chain",
    "problem": "Reading a nested property through an undefined intermediate raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\n  return user.address.city;\n                      ^\n\nTypeError: Cannot read properties of undefined (reading 'city')\n    at getUserCity (/workspace/main.js:2:23)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function getUserCity(user) {\n-  return user.address.city;\n+  return user.address?.city ?? 'unknown';\n }\n console.log(getUserCity({ name: 'Ada' }));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:12.504Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 168,
      "stdout": "unknown\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:12.505Z"
    }
  },
  {
    "id": "fix_node_reduce_empty_array_no_initial",
    "problem": "Array.prototype.reduce on an empty array with no initial value raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:1\nconst total = [].reduce((acc, val) => acc + val);\n                 ^\n\nTypeError: Reduce of empty array with no initial value\n    at Array.reduce (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:1:18)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n-const total = [].reduce((acc, val) => acc + val);\n+const total = [].reduce((acc, val) => acc + val, 0);\n console.log(total);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:12.722Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 106,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:12.722Z"
    }
  },
  {
    "id": "fix_node_circular_json_stringify",
    "problem": "JSON.stringify on an object with a circular reference raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:3\nconsole.log(JSON.stringify(obj));\n                 ^\n\nTypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Object'\n    --- property 'self' closes the circle\n    at JSON.stringify (<anonymous>)\n    at Object.<anonymous> (/workspace/main.js:3:18)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const obj = { name: 'root' };\n obj.self = obj;\n-console.log(JSON.stringify(obj));\n+console.log(JSON.stringify(obj, (key, value) => (key === 'self' ? undefined : value)));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:12.957Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 117,
      "stdout": "{\"name\":\"root\"}\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:12.957Z"
    }
  },
  {
    "id": "fix_node_map_on_null",
    "problem": "Calling .map() on a null value instead of an array raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\n  return items.map((x) => x * 2);\n               ^\n\nTypeError: Cannot read properties of null (reading 'map')\n    at double (/workspace/main.js:2:16)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function double(items) {\n-  return items.map((x) => x * 2);\n+  return (items ?? []).map((x) => x * 2);\n }\n console.log(double(null));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:13.198Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 121,
      "stdout": "[]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:13.198Z"
    }
  },
  {
    "id": "fix_node_unhandled_promise_rejection",
    "problem": "Calling an async function without awaiting or catching its rejection crashes the process",
    "errorType": "UnhandledPromiseRejection",
    "stacktrace": "/workspace/main.js:2\n  throw new Error('config missing');\n        ^\n\nError: config missing\n    at loadConfig (/workspace/main.js:2:9)\n    at Object.<anonymous> (/workspace/main.js:5:1)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,6 +1,13 @@\n async function loadConfig() {\n   throw new Error('config missing');\n }\n \n-loadConfig();\n-console.log('this line runs before the crash is reported');\n+async function main() {\n+  try {\n+    await loadConfig();\n+  } catch (error) {\n+    console.log('handled:', error.message);\n+  }\n+}\n+\n+main();",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:13.437Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 123,
      "stdout": "handled: config missing\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:13.437Z"
    }
  },
  {
    "id": "fix_node_max_call_stack_recursion",
    "problem": "Recursive function without a base case raises RangeError: Maximum call stack size exceeded",
    "errorType": "RangeError",
    "stacktrace": "/workspace/main.js:2\n  return n * factorial(n - 1);\n  ^\n\nRangeError: Maximum call stack size exceeded\n    at factorial (/workspace/main.js:2:3)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n    at factorial (/workspace/main.js:2:14)\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,5 @@\n function factorial(n) {\n+  if (n <= 1) return 1;\n   return n * factorial(n - 1);\n }\n console.log(factorial(5));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:13.679Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 116,
      "stdout": "120\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:13.679Z"
    }
  },
  {
    "id": "fix_node_property_not_a_function",
    "problem": "Calling .push() on a plain object instead of an array raises TypeError: is not a function",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nqueue.push(1);\n      ^\n\nTypeError: queue.push is not a function\n    at Object.<anonymous> (/workspace/main.js:2:7)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n const queue = { items: [] };\n-queue.push(1);\n+queue.items.push(1);\n console.log(queue.items);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:13.942Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 137,
      "stdout": "[ 1 ]\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:13.942Z"
    }
  },
  {
    "id": "fix_node_cannot_find_module",
    "problem": "require() of a relative path that does not exist raises \"Cannot find module\"",
    "errorType": "Error",
    "stacktrace": "node:internal/modules/cjs/loader:1210\n  throw err;\n  ^\n\nError: Cannot find module './missing-utils.js'\nRequire stack:\n- /workspace/main.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)\n    at Module._load (node:internal/modules/cjs/loader:1038:27)\n    at Module.require (node:internal/modules/cjs/loader:1289:19)\n    at require (node:internal/modules/helpers:182:18)\n    at Object.<anonymous> (/workspace/main.js:1:15)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [ '/workspace/main.js' ]\n}\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,5 @@\n-const utils = require('./missing-utils.js');\n+const fs = require('node:fs');\n+const path = '/tmp/utils.js';\n+fs.writeFileSync(path, 'module.exports = { greet: (name) => `hello, ${name}` };');\n+const utils = require(path);\n console.log(utils.greet('world'));",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:14.179Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "hello, world\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:14.179Z"
    }
  },
  {
    "id": "fix_node_const_reassignment",
    "problem": "Reassigning a const-declared variable raises TypeError: Assignment to constant variable",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nretries = retries - 1;\n        ^\n\nTypeError: Assignment to constant variable.\n    at Object.<anonymous> (/workspace/main.js:2:9)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,3 +1,3 @@\n-const retries = 3;\n+let retries = 3;\n retries = retries - 1;\n console.log(retries);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:14.399Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 107,
      "stdout": "2\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:14.399Z"
    }
  },
  {
    "id": "fix_node_block_scope_reference_error",
    "problem": "Referencing a let-declared variable outside the block it was declared in raises ReferenceError",
    "errorType": "ReferenceError",
    "stacktrace": "/workspace/main.js:4\nconsole.log(message);\n            ^\n\nReferenceError: message is not defined\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,5 @@\n+let message;\n if (true) {\n-  let message = 'hello';\n+  message = 'hello';\n }\n console.log(message);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:14.623Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 111,
      "stdout": "hello\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:14.623Z"
    }
  },
  {
    "id": "fix_node_symbol_to_string_conversion",
    "problem": "Implicitly converting a Symbol to a string via template literal raises TypeError",
    "errorType": "TypeError",
    "stacktrace": "/workspace/main.js:2\nconsole.log(`ID: ${id}`);\n                   ^\n\nTypeError: Cannot convert a Symbol value to a string\n    at Object.<anonymous> (/workspace/main.js:2:20)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,2 +1,2 @@\n const id = Symbol('user-id');\n-console.log(`ID: ${id}`);\n+console.log(`ID: ${String(id)}`);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:14.861Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 117,
      "stdout": "ID: Symbol(user-id)\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:14.861Z"
    }
  },
  {
    "id": "fix_node_invalid_array_length",
    "problem": "Constructing an Array with a negative length raises RangeError: Invalid array length",
    "errorType": "RangeError",
    "stacktrace": "/workspace/main.js:2\n  return new Array(size);\n         ^\n\nRangeError: Invalid array length\n    at createBuffer (/workspace/main.js:2:10)\n    at Object.<anonymous> (/workspace/main.js:4:13)\n    at Module._compile (node:internal/modules/cjs/loader:1521:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)\n    at Module.load (node:internal/modules/cjs/loader:1266:32)\n    at Module._load (node:internal/modules/cjs/loader:1091:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)\n    at node:internal/main/run_main_module:28:49\n\nNode.js v20.20.2",
    "environment": {
      "language": "javascript",
      "version": "20"
    },
    "patch": "===================================================================\n--- a/main.js\n+++ b/main.js\n@@ -1,4 +1,4 @@\n function createBuffer(size) {\n-  return new Array(size);\n+  return new Array(Math.max(0, size));\n }\n console.log(createBuffer(-1).length);",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:15.103Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 121,
      "stdout": "0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "node",
      "addedAt": "2026-07-25T15:05:15.103Z"
    }
  },
  {
    "id": "fix_docker_unknown_instruction_typo",
    "problem": "A typo'd Dockerfile instruction (\"RUNN\") fails the build with an unknown-instruction error",
    "errorType": "DockerBuildError",
    "stacktrace": "time=\"2026-07-25T20:35:15+05:30\" level=error msg=\"+(UNHANDLED LOGLEVEL) &imagebuilder.Step{Env:[]string{\\\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\\\"}, Command:\\\"runn\\\", Args:[]string{\\\"\\\"}, Flags:[]string{}, Attrs:map[string]bool(nil), Message:\\\"RUNN \\\", Heredocs:[]parser.Heredoc(nil), Original:\\\"RUNN echo \\\\\\\"hello\\\\\\\"\\\"}\"\nError: building at STEP \"RUNN \": Build error: Unknown instruction: \"RUNN\" &imagebuilder.Step{Env:[]string{\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"}, Command:\"runn\", Args:[]string{\"\"}, Flags:[]string{}, Attrs:map[string]bool(nil), Message:\"RUNN \", Heredocs:[]parser.Heredoc(nil), Original:\"RUNN echo \\\"hello\\\"\"}",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-RUNN echo \"hello\"\n+RUN echo \"hello\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:15.625Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 385,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo \"hello\"\nhello\nCOMMIT hm-seed-verify-2dffd5f9285f\n--> 414d2d6116ec\nSuccessfully tagged localhost/hm-seed-verify-2dffd5f9285f:latest\n414d2d6116ec6007d3a4309d94150e371978d0be945dfe6ebfa2faa5c642f219\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:15.625Z"
    }
  },
  {
    "id": "fix_docker_copy_from_wrong_stage_name",
    "problem": "COPY --from referencing a build stage name that was never defined fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: COPY --from=wrongstage: no stage or image found with that name",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,5 +1,5 @@\n FROM alpine:3.19 AS builder\n RUN echo \"build\" > /out.txt\n \n FROM alpine:3.19\n-COPY --from=wrongstage /out.txt /out.txt\n+COPY --from=builder /out.txt /out.txt",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:25.414Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 6135,
      "stdout": "[1/2] STEP 1/2: FROM alpine:3.19 AS builder\n[1/2] STEP 2/2: RUN echo \"build\" > /out.txt\n--> bb1edd794c05\n[2/2] STEP 1/2: FROM alpine:3.19\n[2/2] STEP 2/2: COPY --from=builder /out.txt /out.txt\n[2/2] COMMIT hm-seed-verify-b56ca62b3d69\n--> acfbc0a0f594\nSuccessfully tagged localhost/hm-seed-verify-b56ca62b3d69:latest\nacfbc0a0f5942625ad50423985be0fe75d661181a436012bdf09335e42922c32\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:25.414Z"
    }
  },
  {
    "id": "fix_docker_copy_missing_context_file",
    "problem": "COPY referencing a file that does not exist in the build context fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"COPY nonexistent-file.txt /app/nonexistent-file.txt\": checking on sources under \"/var/tmp/buildah-context-2867859789/overlay/355970180/merge\": copier: stat: \"/nonexistent-file.txt\": no such file or directory",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-COPY nonexistent-file.txt /app/nonexistent-file.txt\n+RUN mkdir -p /app && echo \"generated at build time\" > /app/nonexistent-file.txt",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:25.881Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 364,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN mkdir -p /app && echo \"generated at build time\" > /app/nonexistent-file.txt\nCOMMIT hm-seed-verify-19a18b634f3f\n--> d2c714119b39\nSuccessfully tagged localhost/hm-seed-verify-19a18b634f3f:latest\nd2c714119b392c38e672151f7828aaac60d10e8bc4e0a79d31e3792b28e58e6e\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:25.881Z"
    }
  },
  {
    "id": "fix_docker_env_missing_value",
    "problem": "An ENV instruction with only a key and no value fails to parse",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: parsing main Dockerfile: /tmp/hm-docker-fixture-GtlYlV/Dockerfile: ENV must have two arguments",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n-ENV APP_PORT\n+ENV APP_PORT=8080\n CMD [\"sh\", \"-c\", \"echo listening on $APP_PORT\"]",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:26.070Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 104,
      "stdout": "STEP 1/3: FROM alpine:3.19\nSTEP 2/3: ENV APP_PORT=8080\n--> 709ce8281072\nSTEP 3/3: CMD [\"sh\", \"-c\", \"echo listening on $APP_PORT\"]\nCOMMIT hm-seed-verify-57d2ea411f75\n--> a07af88cc266\nSuccessfully tagged localhost/hm-seed-verify-57d2ea411f75:latest\na07af88cc266752bca61d08456b76353f5f2bb909cf2db79ec144107d08dae23\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:26.070Z"
    }
  },
  {
    "id": "fix_docker_missing_from_first_instruction",
    "problem": "A Dockerfile whose first instruction is not FROM fails to build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: reading multiple stages: stage 1 requires a FROM instruction (\"\")",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n-RUN echo \"no from\"\n FROM alpine:3.19\n+RUN echo \"no from\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:26.527Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 382,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo \"no from\"\nno from\nCOMMIT hm-seed-verify-6853454a7e28\n--> e772cf0dff50\nSuccessfully tagged localhost/hm-seed-verify-6853454a7e28:latest\ne772cf0dff50c1cf9e8fbeb735f614ce47f0f66ae1472e9cd55cb197f6d50511\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:26.527Z"
    }
  },
  {
    "id": "fix_docker_healthcheck_invalid_interval",
    "problem": "A HEALTHCHECK with a non-duration --interval value fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"HEALTHCHECK --interval=notanumber CMD echo ok\": time: invalid duration \"notanumber\"",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-HEALTHCHECK --interval=notanumber CMD echo ok\n+HEALTHCHECK --interval=30s CMD echo ok",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:26.672Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 63,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: HEALTHCHECK --interval=30s CMD echo ok\nCOMMIT hm-seed-verify-bbfb53275da0\n--> e0c6e937cff1\nSuccessfully tagged localhost/hm-seed-verify-bbfb53275da0:latest\ne0c6e937cff1113ea28bcc09cde38d956c2933b3dee17c58e190f1a7ef2efb0b\n",
      "stderr": "time=\"2026-07-25T20:35:26+05:30\" level=warning msg=\"HEALTHCHECK is not supported for OCI image format and will be ignored. Must use `docker` format\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:26.672Z"
    }
  },
  {
    "id": "fix_docker_copy_from_invalid_stage_index",
    "problem": "COPY --from referencing a numeric build-stage index that does not exist fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: COPY --from=5: no stage or image found with that name",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n FROM alpine:3.19\n-COPY --from=5 /etc/hostname /tmp/hostname\n+COPY --from=0 /etc/hostname /tmp/hostname",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:33.430Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 4495,
      "stdout": "[1/2] STEP 1/1: FROM alpine:3.19\n--> 83b2b6703a62\n[2/2] STEP 1/2: FROM alpine:3.19\n[2/2] STEP 2/2: COPY --from=0 /etc/hostname /tmp/hostname\n[2/2] COMMIT hm-seed-verify-eac313a0ffb6\n--> 285d699bcdf1\nSuccessfully tagged localhost/hm-seed-verify-eac313a0ffb6:latest\n285d699bcdf1547236a21ee43378ff3a62aca49f6ef4b7cfde163337e1bc2868\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:33.430Z"
    }
  },
  {
    "id": "fix_docker_workdir_missing_argument",
    "problem": "A WORKDIR instruction with no path argument fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"WORKDIR \": WORKDIR requires exactly one argument",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-WORKDIR\n+WORKDIR /app",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:33.584Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 69,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: WORKDIR /app\nCOMMIT hm-seed-verify-9f66743bf750\n--> 2ccbe216a1fd\nSuccessfully tagged localhost/hm-seed-verify-9f66743bf750:latest\n2ccbe216a1fd365f9c9feef6f84fcb292d56989f7798db441092794dd87145b0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:33.584Z"
    }
  },
  {
    "id": "fix_docker_user_nonexistent",
    "problem": "A USER instruction referencing a user that does not exist in the image fails subsequent RUN steps",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"RUN echo hi\": determining run uid: user: unknown user error looking up user \"nonexistentuser\"",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,3 +1,3 @@\n FROM alpine:3.19\n-USER nonexistentuser\n+USER root\n RUN echo hi",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:34.411Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 528,
      "stdout": "STEP 1/3: FROM alpine:3.19\nSTEP 2/3: USER root\n--> 3e709aa6df93\nSTEP 3/3: RUN echo hi\nhi\nCOMMIT hm-seed-verify-90b2d0eacbf1\n--> 51317a7b7d45\nSuccessfully tagged localhost/hm-seed-verify-90b2d0eacbf1:latest\n51317a7b7d4514ed0facf27420f5292ab6b5126f4e08934bf59da92ac02fb8a0\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:34.411Z"
    }
  },
  {
    "id": "fix_docker_stopsignal_invalid",
    "problem": "A STOPSIGNAL instruction with an invalid signal name fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"STOPSIGNAL NOTASIGNAL\": Invalid signal: NOTASIGNAL",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-STOPSIGNAL NOTASIGNAL\n+STOPSIGNAL SIGTERM",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:34.554Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 63,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: STOPSIGNAL SIGTERM\nCOMMIT hm-seed-verify-495750eb2e84\n--> db9ee3ad2b48\nSuccessfully tagged localhost/hm-seed-verify-495750eb2e84:latest\ndb9ee3ad2b48d69090ff81853b4f22c489a9865500e29a8c2dcd67ccf5c93d07\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:34.554Z"
    }
  },
  {
    "id": "fix_docker_arg_undeclared_before_from",
    "problem": "Referencing an ARG in FROM without declaring it beforehand leaves FROM with no image and fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: determining starting point for build: no FROM statement found",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,3 @@\n+ARG BASE_IMAGE=alpine:3.19\n FROM ${BASE_IMAGE}\n RUN echo hi",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:34.991Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 364,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: RUN echo hi\nhi\nCOMMIT hm-seed-verify-5132f1d0cc09\n--> 758449abaaa5\nSuccessfully tagged localhost/hm-seed-verify-5132f1d0cc09:latest\n758449abaaa5866a70e5ef7cd77713fa109cd76bb933f069bb4c45d73b1d1555\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:34.991Z"
    }
  },
  {
    "id": "fix_docker_shell_invalid_form",
    "problem": "A SHELL instruction not written as a JSON array fails the build",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"SHELL /bin/sh -c\": SHELL requires the arguments to be in JSON form",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-SHELL /bin/sh -c\n+SHELL [\"/bin/sh\", \"-c\"]",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:35.160Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 75,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: SHELL [\"/bin/sh\", \"-c\"]\nCOMMIT hm-seed-verify-c6b225b94ebe\n--> 66910b46705f\nSuccessfully tagged localhost/hm-seed-verify-c6b225b94ebe:latest\n66910b46705ffc03bff5ac60f951e7d848fec2eeba375f0052c6110295169419\n",
      "stderr": "time=\"2026-07-25T20:35:35+05:30\" level=warning msg=\"SHELL is not persisted in the OCI image format, [/bin/sh -c] will be used for RUN subsequent instructions to build this image but will not be present in saved image which may affect any images that use this as a base. Must use `docker` format to persist in saved image\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:35.160Z"
    }
  },
  {
    "id": "fix_docker_onbuild_forbidden_trigger",
    "problem": "ONBUILD wrapping a FROM instruction fails the build, since FROM is not allowed as an ONBUILD trigger",
    "errorType": "DockerBuildError",
    "stacktrace": "Error: building at STEP \"ONBUILD from alpine:3.19\": FROM isn't allowed as an ONBUILD trigger",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/Dockerfile\n+++ b/Dockerfile\n@@ -1,2 +1,2 @@\n FROM alpine:3.19\n-ONBUILD FROM alpine:3.19\n+ONBUILD RUN echo \"building downstream image\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:35.319Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 70,
      "stdout": "STEP 1/2: FROM alpine:3.19\nSTEP 2/2: ONBUILD RUN echo \"building downstream image\"\nCOMMIT hm-seed-verify-058fa4ab2644\n--> ed5cd76a66df\nSuccessfully tagged localhost/hm-seed-verify-058fa4ab2644:latest\ned5cd76a66df4437cca5ff03e6673fb9b099c68abf6496b09770c9144f277940\n",
      "stderr": "time=\"2026-07-25T20:35:35+05:30\" level=warning msg=\"ONBUILD is not supported for OCI image format, RUN echo \\\"building downstream image\\\" will be ignored. Must use `docker` format\"\n"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:35.319Z"
    }
  },
  {
    "id": "fix_docker_compose_bad_indentation",
    "problem": "A docker-compose.yml with a stray extra indentation level fails YAML parsing",
    "errorType": "ComposeConfigError",
    "stacktrace": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0mCRITICAL:podman_compose:Compose file contains an error:\nmapping values are not allowed here\n  in \"/tmp/hm-docker-fixture-nyy4Gg/compose.yml\", line 4, column 11\nError: executing /usr/bin/podman-compose -f /tmp/hm-docker-fixture-nyy4Gg/compose.yml config: exit status 1",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/docker-compose.yml\n+++ b/docker-compose.yml\n@@ -1,5 +1,5 @@\n services:\n   web:\n     image: alpine:3.19\n-     ports:\n+    ports:\n       - \"8080:80\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:35.567Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 116,
      "stdout": "services:\n  web:\n    image: alpine:3.19\n    ports:\n    - 8080:80\n\n",
      "stderr": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0m"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:35.567Z"
    }
  },
  {
    "id": "fix_docker_compose_tab_character",
    "problem": "A docker-compose.yml containing a tab character for indentation fails YAML parsing",
    "errorType": "ComposeConfigError",
    "stacktrace": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0mCRITICAL:podman_compose:Compose file contains an error:\nwhile scanning for the next token\nfound character '\\t' that cannot start any token\n  in \"/tmp/hm-docker-fixture-yu3LS4/compose.yml\", line 3, column 1\nError: executing /usr/bin/podman-compose -f /tmp/hm-docker-fixture-yu3LS4/compose.yml config: exit status 1",
    "environment": {
      "language": "docker"
    },
    "patch": "===================================================================\n--- a/docker-compose.yml\n+++ b/docker-compose.yml\n@@ -1,3 +1,3 @@\n services:\n   web:\n-\timage: alpine:3.19\n+    image: alpine:3.19",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:35.789Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 115,
      "stdout": "services:\n  web:\n    image: alpine:3.19\n\n",
      "stderr": "\u001b[4m>>>> Executing external compose provider \"/usr/bin/podman-compose\". Please see podman-compose(1) for how to disable this message. <<<<\n\n\u001b[0m"
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "docker",
      "addedAt": "2026-07-25T15:05:35.789Z"
    }
  },
  {
    "id": "fix_general_array_syntax_in_posix_sh",
    "problem": "A bash-style array declaration used in a script run by POSIX sh raises a syntax error",
    "errorType": "ShellSyntaxError",
    "stacktrace": "main.sh: line 1: syntax error: unexpected \"(\"",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,5 @@\n-items=(apple banana cherry)\n-echo \"${items[0]}\"\n+items=\"apple banana cherry\"\n+for item in $items; do\n+  echo \"$item\"\n+  break\n+done",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:35.972Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 95,
      "stdout": "apple\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:35.972Z"
    }
  },
  {
    "id": "fix_general_source_missing_file",
    "problem": "Sourcing an environment file that does not exist fails the script",
    "errorType": "ShellSourceError",
    "stacktrace": "main.sh: .: line 1: can't open '/workspace/nonexistent-env.sh': No such file or directory",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,4 @@\n-. /workspace/nonexistent-env.sh\n+if [ -f /workspace/nonexistent-env.sh ]; then\n+  . /workspace/nonexistent-env.sh\n+fi\n echo \"loaded\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:36.162Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 93,
      "stdout": "loaded\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:36.162Z"
    }
  },
  {
    "id": "fix_general_crlf_line_endings",
    "problem": "A script saved with CRLF line endings corrupts the shebang interpreter path, so it cannot be executed",
    "errorType": "BadInterpreter",
    "stacktrace": "sh: /tmp/main.sh: not found",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,2 @@\n-#!/bin/sh\r\n-echo hello\r\n+#!/bin/sh\n+echo hello",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:36.341Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 92,
      "stdout": "hello\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:36.341Z"
    }
  },
  {
    "id": "fix_general_env_case_sensitivity",
    "problem": "Comparing an environment variable value against an expected string without normalizing case rejects a valid value",
    "errorType": "EnvironmentMismatch",
    "stacktrace": "not recognized as production, exiting",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,6 +1,7 @@\n ENVIRONMENT=\"Production\"\n-if [ \"$ENVIRONMENT\" != \"production\" ]; then\n+NORMALIZED=$(echo \"$ENVIRONMENT\" | tr '[:upper:]' '[:lower:]')\n+if [ \"$NORMALIZED\" != \"production\" ]; then\n   echo \"not recognized as production, exiting\"\n   exit 1\n fi\n echo \"running in production mode\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:36.526Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 99,
      "stdout": "running in production mode\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:36.526Z"
    }
  },
  {
    "id": "fix_general_path_override_breaks_lookup",
    "problem": "Overwriting PATH instead of extending it makes previously-available commands unresolvable",
    "errorType": "CommandNotFound",
    "stacktrace": "main.sh: line 2: grep: not found",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,2 @@\n-PATH=/nonexistent-only\n+PATH=\"/usr/bin:/bin:$PATH\"\n echo \"needle\" | grep \"needle\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:36.714Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 97,
      "stdout": "needle\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:36.714Z"
    }
  },
  {
    "id": "fix_general_home_relative_path_unset",
    "problem": "Building a path from $HOME without checking it is set reads from the filesystem root instead",
    "errorType": "FileNotFoundError",
    "stacktrace": "cat: can't open '/.myconfig': No such file or directory",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,5 @@\n unset HOME\n+HOME=\"${HOME:-/tmp}\"\n+mkdir -p \"$HOME\"\n+echo \"example config\" > \"$HOME/.myconfig\"\n cat \"$HOME/.myconfig\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:36.897Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 94,
      "stdout": "example config\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:36.897Z"
    }
  },
  {
    "id": "fix_general_bad_shebang_interpreter",
    "problem": "A typo in the shebang interpreter path makes the script unexecutable",
    "errorType": "BadInterpreter",
    "stacktrace": "sh: /tmp/main.sh: not found",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,2 @@\n-#!/bin/shh\n+#!/bin/sh\n echo hello",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:37.078Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 89,
      "stdout": "hello\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:37.078Z"
    }
  },
  {
    "id": "fix_general_octal_like_shell_arithmetic",
    "problem": "A zero-padded number in shell arithmetic is parsed as invalid octal, raising an arithmetic syntax error",
    "errorType": "ShellArithmeticError",
    "stacktrace": "main.sh: line 2: arithmetic syntax error",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,3 +1,4 @@\n COUNT=\"08\"\n+COUNT=$((10#$COUNT))\n RESULT=$((COUNT + 1))\n echo \"$RESULT\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:37.268Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 92,
      "stdout": "9\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:37.268Z"
    }
  },
  {
    "id": "fix_general_subshell_pipe_variable_scoping",
    "problem": "Piping into a while-read loop runs it in a subshell, so variables it sets are lost once the pipeline ends",
    "errorType": "VariableScopingError",
    "stacktrace": "count=0\nexpected 3, got 0",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,8 +1,12 @@\n COUNT=0\n-printf \"a\\nb\\nc\\n\" | while read -r line; do\n+while read -r line; do\n   COUNT=$((COUNT + 1))\n-done\n+done <<EOF\n+a\n+b\n+c\n+EOF\n echo \"count=$COUNT\"\n if [ \"$COUNT\" -ne 3 ]; then\n   echo \"expected 3, got $COUNT\"\n   exit 1",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:37.444Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 86,
      "stdout": "count=3\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:37.444Z"
    }
  },
  {
    "id": "fix_general_set_u_unbound_variable",
    "problem": "Running with `set -u` and referencing an unset environment variable aborts the script",
    "errorType": "UnboundVariableError",
    "stacktrace": "main.sh: line 2: DEPLOY_TARGET: parameter not set",
    "environment": {
      "language": "general"
    },
    "patch": "===================================================================\n--- a/main.sh\n+++ b/main.sh\n@@ -1,2 +1,3 @@\n set -u\n+DEPLOY_TARGET=\"${DEPLOY_TARGET:-staging}\"\n echo \"Deploying to: $DEPLOY_TARGET\"",
    "verification": {
      "status": "PASS",
      "score": 0.9,
      "lastVerified": "2026-07-25T15:05:37.623Z",
      "sandbox": "docker",
      "exitCode": 0,
      "durationMs": 90,
      "stdout": "Deploying to: staging\n",
      "stderr": ""
    },
    "metrics": {
      "reuseCount": 0
    },
    "provenance": {
      "source": "seed",
      "category": "general",
      "addedAt": "2026-07-25T15:05:37.623Z"
    }
  }
];
