import type { SeedFixtureDefinition } from './index.js';

/**
 * 15 stable-ID Docker fixtures. Every one was empirically confirmed against
 * this machine's real `podman build`/`podman compose config` before being
 * written here — Dockerfile/Buildah error messages vary across versions, so
 * nothing here is guessed. Verified via controlled host-level builds and
 * config validation (never nested inside a sandboxed container — that would
 * require mounting the Docker socket into an untrusted container, which
 * Decision 005/Checkpoint 5 forbid). See DOUBTS.md for why compose semantic
 * validation (missing image, bad port format) isn't covered: `podman compose
 * config` doesn't actually enforce it, only YAML-syntax-level errors do.
 */

const ENV = { language: 'docker' };

export const DOCKER_SEED_FIXTURES: SeedFixtureDefinition[] = [
  {
    id: 'fix_docker_unknown_instruction_typo',
    problem: 'A typo\'d Dockerfile instruction ("RUNN") fails the build with an unknown-instruction error',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nRUNN echo "hello"\n`,
    fixedCode: `FROM alpine:3.19\nRUN echo "hello"\n`,
  },
  {
    id: 'fix_docker_copy_from_wrong_stage_name',
    problem: 'COPY --from referencing a build stage name that was never defined fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19 AS builder\nRUN echo "build" > /out.txt\n\nFROM alpine:3.19\nCOPY --from=wrongstage /out.txt /out.txt\n`,
    fixedCode: `FROM alpine:3.19 AS builder\nRUN echo "build" > /out.txt\n\nFROM alpine:3.19\nCOPY --from=builder /out.txt /out.txt\n`,
  },
  {
    id: 'fix_docker_copy_missing_context_file',
    problem: 'COPY referencing a file that does not exist in the build context fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nCOPY nonexistent-file.txt /app/nonexistent-file.txt\n`,
    fixedCode: `FROM alpine:3.19\nRUN mkdir -p /app && echo "generated at build time" > /app/nonexistent-file.txt\n`,
  },
  {
    id: 'fix_docker_env_missing_value',
    problem: 'An ENV instruction with only a key and no value fails to parse',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nENV APP_PORT\nCMD ["sh", "-c", "echo listening on $APP_PORT"]\n`,
    fixedCode: `FROM alpine:3.19\nENV APP_PORT=8080\nCMD ["sh", "-c", "echo listening on $APP_PORT"]\n`,
  },
  {
    id: 'fix_docker_missing_from_first_instruction',
    problem: 'A Dockerfile whose first instruction is not FROM fails to build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `RUN echo "no from"\nFROM alpine:3.19\n`,
    fixedCode: `FROM alpine:3.19\nRUN echo "no from"\n`,
  },
  {
    id: 'fix_docker_healthcheck_invalid_interval',
    problem: 'A HEALTHCHECK with a non-duration --interval value fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nHEALTHCHECK --interval=notanumber CMD echo ok\n`,
    fixedCode: `FROM alpine:3.19\nHEALTHCHECK --interval=30s CMD echo ok\n`,
  },
  {
    id: 'fix_docker_copy_from_invalid_stage_index',
    problem: 'COPY --from referencing a numeric build-stage index that does not exist fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nFROM alpine:3.19\nCOPY --from=5 /etc/hostname /tmp/hostname\n`,
    fixedCode: `FROM alpine:3.19\nFROM alpine:3.19\nCOPY --from=0 /etc/hostname /tmp/hostname\n`,
  },
  {
    id: 'fix_docker_workdir_missing_argument',
    problem: 'A WORKDIR instruction with no path argument fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nWORKDIR\n`,
    fixedCode: `FROM alpine:3.19\nWORKDIR /app\n`,
  },
  {
    id: 'fix_docker_user_nonexistent',
    problem: 'A USER instruction referencing a user that does not exist in the image fails subsequent RUN steps',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nUSER nonexistentuser\nRUN echo hi\n`,
    fixedCode: `FROM alpine:3.19\nUSER root\nRUN echo hi\n`,
  },
  {
    id: 'fix_docker_stopsignal_invalid',
    problem: 'A STOPSIGNAL instruction with an invalid signal name fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nSTOPSIGNAL NOTASIGNAL\n`,
    fixedCode: `FROM alpine:3.19\nSTOPSIGNAL SIGTERM\n`,
  },
  {
    id: 'fix_docker_arg_undeclared_before_from',
    problem: 'Referencing an ARG in FROM without declaring it beforehand leaves FROM with no image and fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM \${BASE_IMAGE}\nRUN echo hi\n`,
    fixedCode: `ARG BASE_IMAGE=alpine:3.19\nFROM \${BASE_IMAGE}\nRUN echo hi\n`,
  },
  {
    id: 'fix_docker_shell_invalid_form',
    problem: 'A SHELL instruction not written as a JSON array fails the build',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nSHELL /bin/sh -c\n`,
    fixedCode: `FROM alpine:3.19\nSHELL ["/bin/sh", "-c"]\n`,
  },
  {
    id: 'fix_docker_onbuild_forbidden_trigger',
    problem: 'ONBUILD wrapping a FROM instruction fails the build, since FROM is not allowed as an ONBUILD trigger',
    errorType: 'DockerBuildError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'docker-build',
    testCommand: '',
    fileExtension: 'Dockerfile',
    brokenCode: `FROM alpine:3.19\nONBUILD FROM alpine:3.19\n`,
    fixedCode: `FROM alpine:3.19\nONBUILD RUN echo "building downstream image"\n`,
  },
  {
    id: 'fix_docker_compose_bad_indentation',
    problem: 'A docker-compose.yml with a stray extra indentation level fails YAML parsing',
    errorType: 'ComposeConfigError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'compose-config',
    testCommand: '',
    fileExtension: 'yml',
    brokenCode: `services:\n  web:\n    image: alpine:3.19\n     ports:\n      - "8080:80"\n`,
    fixedCode: `services:\n  web:\n    image: alpine:3.19\n    ports:\n      - "8080:80"\n`,
  },
  {
    id: 'fix_docker_compose_tab_character',
    problem: 'A docker-compose.yml containing a tab character for indentation fails YAML parsing',
    errorType: 'ComposeConfigError',
    category: 'docker',
    environment: ENV,
    verificationMethod: 'compose-config',
    testCommand: '',
    fileExtension: 'yml',
    brokenCode: `services:\n  web:\n\timage: alpine:3.19\n`,
    fixedCode: `services:\n  web:\n    image: alpine:3.19\n`,
  },
];
