import type { SeedFixtureDefinition } from './index.js';

/**
 * 15 stable-ID Node.js/TypeScript fixtures, verified by `npm run seed:verify`
 * against the real Docker/podman sandbox. Node.js-builtin-only (no npm
 * packages, same network constraint as the Python corpus). TypeScript
 * compile-time errors specifically are deferred for the same reason: the
 * `node:20-slim` image has no `tsc`/`ts-node`/`tsx` and no network to install
 * them, so only runtime JS/Node behavior (equally relevant to compiled
 * TypeScript) is covered here. See DOUBTS.md.
 */

const ENV = { language: 'javascript', version: '20' };
const TEST_COMMAND = 'node main.js';
const EXT = 'js';

export const NODE_SEED_FIXTURES: SeedFixtureDefinition[] = [
  {
    id: 'fix_node_require_in_esm',
    problem: "ReferenceError: require is not defined in ES module scope",
    errorType: 'ReferenceError',
    category: 'node',
    environment: ENV,
    testCommand: 'cp main.js /tmp/main.mjs && node /tmp/main.mjs',
    fileExtension: EXT,
    brokenCode: `const path = require('node:path');\nconsole.log(path.basename('/tmp/main.mjs'));\n`,
    fixedCode: `import path from 'node:path';\nconsole.log(path.basename('/tmp/main.mjs'));\n`,
  },
  {
    id: 'fix_node_import_in_commonjs',
    problem: 'ES module "import" statement used in a file Node treats as CommonJS raises a SyntaxError',
    errorType: 'SyntaxError',
    category: 'node',
    environment: ENV,
    // .cjs always forces CommonJS parsing (no ESM-syntax auto-detection,
    // unlike a plain .js file on recent Node 20.x patch releases).
    testCommand: 'cp main.js /tmp/main.cjs && node /tmp/main.cjs',
    fileExtension: EXT,
    brokenCode: `import { readFileSync } from 'node:fs';\nconsole.log(typeof readFileSync);\n`,
    fixedCode: `const { readFileSync } = require('node:fs');\nconsole.log(typeof readFileSync);\n`,
  },
  {
    id: 'fix_node_json_parse_empty_string',
    problem: 'JSON.parse on an empty string raises SyntaxError: Unexpected end of JSON input',
    errorType: 'SyntaxError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const raw = "";\nconst data = JSON.parse(raw);\nconsole.log(data);\n`,
    fixedCode: `const raw = "";\nconst data = raw ? JSON.parse(raw) : {};\nconsole.log(data);\n`,
  },
  {
    id: 'fix_node_undefined_property_chain',
    problem: 'Reading a nested property through an undefined intermediate raises TypeError',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `function getUserCity(user) {\n  return user.address.city;\n}\nconsole.log(getUserCity({ name: 'Ada' }));\n`,
    fixedCode: `function getUserCity(user) {\n  return user.address?.city ?? 'unknown';\n}\nconsole.log(getUserCity({ name: 'Ada' }));\n`,
  },
  {
    id: 'fix_node_reduce_empty_array_no_initial',
    problem: 'Array.prototype.reduce on an empty array with no initial value raises TypeError',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const total = [].reduce((acc, val) => acc + val);\nconsole.log(total);\n`,
    fixedCode: `const total = [].reduce((acc, val) => acc + val, 0);\nconsole.log(total);\n`,
  },
  {
    id: 'fix_node_circular_json_stringify',
    problem: 'JSON.stringify on an object with a circular reference raises TypeError',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const obj = { name: 'root' };\nobj.self = obj;\nconsole.log(JSON.stringify(obj));\n`,
    fixedCode: `const obj = { name: 'root' };\nobj.self = obj;\nconsole.log(JSON.stringify(obj, (key, value) => (key === 'self' ? undefined : value)));\n`,
  },
  {
    id: 'fix_node_map_on_null',
    problem: 'Calling .map() on a null value instead of an array raises TypeError',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `function double(items) {\n  return items.map((x) => x * 2);\n}\nconsole.log(double(null));\n`,
    fixedCode: `function double(items) {\n  return (items ?? []).map((x) => x * 2);\n}\nconsole.log(double(null));\n`,
  },
  {
    id: 'fix_node_unhandled_promise_rejection',
    problem: 'Calling an async function without awaiting or catching its rejection crashes the process',
    errorType: 'UnhandledPromiseRejection',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `async function loadConfig() {\n  throw new Error('config missing');\n}\n\nloadConfig();\nconsole.log('this line runs before the crash is reported');\n`,
    fixedCode: `async function loadConfig() {\n  throw new Error('config missing');\n}\n\nasync function main() {\n  try {\n    await loadConfig();\n  } catch (error) {\n    console.log('handled:', error.message);\n  }\n}\n\nmain();\n`,
  },
  {
    id: 'fix_node_max_call_stack_recursion',
    problem: 'Recursive function without a base case raises RangeError: Maximum call stack size exceeded',
    errorType: 'RangeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `function factorial(n) {\n  return n * factorial(n - 1);\n}\nconsole.log(factorial(5));\n`,
    fixedCode: `function factorial(n) {\n  if (n <= 1) return 1;\n  return n * factorial(n - 1);\n}\nconsole.log(factorial(5));\n`,
  },
  {
    id: 'fix_node_property_not_a_function',
    problem: 'Calling .push() on a plain object instead of an array raises TypeError: is not a function',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const queue = { items: [] };\nqueue.push(1);\nconsole.log(queue.items);\n`,
    fixedCode: `const queue = { items: [] };\nqueue.items.push(1);\nconsole.log(queue.items);\n`,
  },
  {
    id: 'fix_node_cannot_find_module',
    problem: 'require() of a relative path that does not exist raises "Cannot find module"',
    errorType: 'Error',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const utils = require('./missing-utils.js');\nconsole.log(utils.greet('world'));\n`,
    fixedCode: `const fs = require('node:fs');\nconst path = '/tmp/utils.js';\nfs.writeFileSync(path, 'module.exports = { greet: (name) => \`hello, \${name}\` };');\nconst utils = require(path);\nconsole.log(utils.greet('world'));\n`,
  },
  {
    id: 'fix_node_const_reassignment',
    problem: 'Reassigning a const-declared variable raises TypeError: Assignment to constant variable',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const retries = 3;\nretries = retries - 1;\nconsole.log(retries);\n`,
    fixedCode: `let retries = 3;\nretries = retries - 1;\nconsole.log(retries);\n`,
  },
  {
    id: 'fix_node_block_scope_reference_error',
    problem: 'Referencing a let-declared variable outside the block it was declared in raises ReferenceError',
    errorType: 'ReferenceError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `if (true) {\n  let message = 'hello';\n}\nconsole.log(message);\n`,
    fixedCode: `let message;\nif (true) {\n  message = 'hello';\n}\nconsole.log(message);\n`,
  },
  {
    id: 'fix_node_symbol_to_string_conversion',
    problem: 'Implicitly converting a Symbol to a string via template literal raises TypeError',
    errorType: 'TypeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `const id = Symbol('user-id');\nconsole.log(\`ID: \${id}\`);\n`,
    fixedCode: `const id = Symbol('user-id');\nconsole.log(\`ID: \${String(id)}\`);\n`,
  },
  {
    id: 'fix_node_invalid_array_length',
    problem: 'Constructing an Array with a negative length raises RangeError: Invalid array length',
    errorType: 'RangeError',
    category: 'node',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `function createBuffer(size) {\n  return new Array(size);\n}\nconsole.log(createBuffer(-1).length);\n`,
    fixedCode: `function createBuffer(size) {\n  return new Array(Math.max(0, size));\n}\nconsole.log(createBuffer(-1).length);\n`,
  },
];
