import type { SeedFixtureDefinition } from './index.js';

/**
 * 20 stable-ID Python fixtures, verified by `npm run seed:verify` against the
 * real Docker/podman sandbox. Deliberately stdlib-only (no third-party
 * packages): the sandbox runs with `--network none`, so nothing can be
 * `pip install`-ed at verification time. See DOUBTS.md for the reasoning and
 * what would be needed to cover third-party-dependency fixes (e.g. pydantic
 * v1->v2 migrations) in a future checkpoint.
 */

const ENV = { language: 'python', version: '3.11' };
const TEST_COMMAND = 'python3 main.py';
const EXT = 'py';

export const PYTHON_SEED_FIXTURES: SeedFixtureDefinition[] = [
  {
    id: 'fix_python_print_statement_syntax',
    problem: 'Python 2 print statement syntax raises a SyntaxError under Python 3',
    errorType: 'SyntaxError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `print "hello world"\n`,
    fixedCode: `print("hello world")\n`,
  },
  {
    id: 'fix_python_except_comma_syntax',
    problem: 'Python 2 "except Exception, e:" syntax raises a SyntaxError under Python 3',
    errorType: 'SyntaxError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `try:\n    raise ValueError("bad value")\nexcept ValueError, e:\n    print(e)\n`,
    fixedCode: `try:\n    raise ValueError("bad value")\nexcept ValueError as e:\n    print(e)\n`,
  },
  {
    id: 'fix_python_collections_abc_import',
    problem: "ImportError: cannot import name 'Mapping' from 'collections' on Python 3.10+",
    errorType: 'ImportError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `from collections import Mapping\n\nprint(issubclass(dict, Mapping))\n`,
    fixedCode: `from collections.abc import Mapping\n\nprint(issubclass(dict, Mapping))\n`,
  },
  {
    id: 'fix_python_str_int_concat',
    problem: "TypeError when concatenating a string literal with an int without str() conversion",
    errorType: 'TypeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `count = 5\nprint("Total: " + count)\n`,
    fixedCode: `count = 5\nprint("Total: " + str(count))\n`,
  },
  {
    id: 'fix_python_zero_division_unguarded',
    problem: 'Unguarded division by a value that can be zero raises ZeroDivisionError',
    errorType: 'ZeroDivisionError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def average(total, count):\n    return total / count\n\nprint(average(10, 0))\n`,
    fixedCode: `def average(total, count):\n    if count == 0:\n        return 0\n    return total / count\n\nprint(average(10, 0))\n`,
  },
  {
    id: 'fix_python_keyerror_dict_access',
    problem: 'Direct dict subscript access on a possibly-missing key raises KeyError',
    errorType: 'KeyError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `config = {"host": "localhost"}\nprint(config["port"])\n`,
    fixedCode: `config = {"host": "localhost"}\nprint(config.get("port", 8080))\n`,
  },
  {
    id: 'fix_python_index_off_by_one',
    problem: 'Off-by-one indexing with len(lst) instead of len(lst)-1 raises IndexError',
    errorType: 'IndexError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `items = [10, 20, 30]\nprint(items[len(items)])\n`,
    fixedCode: `items = [10, 20, 30]\nprint(items[len(items) - 1])\n`,
  },
  {
    id: 'fix_python_missing_return_none_attribute',
    problem: "Function missing a return statement implicitly returns None, causing AttributeError on the caller side",
    errorType: 'AttributeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def build_list(items):\n    result = []\n    for item in items:\n        result.append(item * 2)\n\nvalues = build_list([1, 2, 3])\nvalues.append(4)\nprint(values)\n`,
    fixedCode: `def build_list(items):\n    result = []\n    for item in items:\n        result.append(item * 2)\n    return result\n\nvalues = build_list([1, 2, 3])\nvalues.append(4)\nprint(values)\n`,
  },
  {
    id: 'fix_python_unbound_local_variable',
    problem: 'Assigning to a module-level variable name inside a function without "global" raises UnboundLocalError',
    errorType: 'UnboundLocalError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `counter = 0\n\ndef increment():\n    counter = counter + 1\n    return counter\n\nprint(increment())\n`,
    fixedCode: `counter = 0\n\ndef increment():\n    global counter\n    counter = counter + 1\n    return counter\n\nprint(increment())\n`,
  },
  {
    id: 'fix_python_recursion_missing_base_case',
    problem: 'Recursive function without a base case raises RecursionError',
    errorType: 'RecursionError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def factorial(n):\n    return n * factorial(n - 1)\n\nprint(factorial(5))\n`,
    fixedCode: `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(5))\n`,
  },
  {
    id: 'fix_python_json_decode_empty_string',
    problem: 'Parsing an empty string with json.loads raises JSONDecodeError',
    errorType: 'JSONDecodeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `import json\n\nraw = ""\ndata = json.loads(raw)\nprint(data)\n`,
    fixedCode: `import json\n\nraw = ""\ndata = json.loads(raw) if raw else {}\nprint(data)\n`,
  },
  {
    id: 'fix_python_file_not_found_unguarded',
    problem: 'Opening a file that does not exist without a fallback raises FileNotFoundError',
    errorType: 'FileNotFoundError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `with open("/tmp/hm_missing_config.json") as f:\n    print(f.read())\n`,
    fixedCode: `import os\n\npath = "/tmp/hm_missing_config.json"\nif not os.path.exists(path):\n    with open(path, "w") as f:\n        f.write("{}")\nwith open(path) as f:\n    print(f.read())\n`,
  },
  {
    id: 'fix_python_returns_count_not_iterable',
    problem: 'Function returns a count instead of the collection, causing TypeError when the caller iterates over it',
    errorType: 'TypeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def get_active_items(items):\n    active = [item for item in items if item.get("active")]\n    return len(active)\n\nfor item in get_active_items([{"active": True}, {"active": False}]):\n    print(item)\n`,
    fixedCode: `def get_active_items(items):\n    active = [item for item in items if item.get("active")]\n    return active\n\nfor item in get_active_items([{"active": True}, {"active": False}]):\n    print(item)\n`,
  },
  {
    id: 'fix_python_dict_changed_size_during_iteration',
    problem: 'Deleting dict keys while iterating directly over the dict raises RuntimeError',
    errorType: 'RuntimeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `data = {"a": 1, "b": -1, "c": 2, "d": -2}\nfor key in data:\n    if data[key] < 0:\n        del data[key]\nprint(data)\n`,
    fixedCode: `data = {"a": 1, "b": -1, "c": 2, "d": -2}\nfor key in list(data.keys()):\n    if data[key] < 0:\n        del data[key]\nprint(data)\n`,
  },
  {
    id: 'fix_python_name_error_conditional_assignment',
    problem: 'A variable only assigned inside an untaken branch raises NameError when referenced afterward',
    errorType: 'NameError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `condition = False\nif condition:\n    message = "hello"\nprint(message)\n`,
    fixedCode: `condition = False\nmessage = "default"\nif condition:\n    message = "hello"\nprint(message)\n`,
  },
  {
    id: 'fix_python_missing_required_argument',
    problem: 'Calling a function without a required positional argument raises TypeError',
    errorType: 'TypeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def greet(name, greeting):\n    return f"{greeting}, {name}!"\n\nprint(greet("World"))\n`,
    fixedCode: `def greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"\n\nprint(greet("World"))\n`,
  },
  {
    id: 'fix_python_int_conversion_unvalidated',
    problem: 'Converting a non-numeric string with int() without validation raises ValueError',
    errorType: 'ValueError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `value = "abc"\nnumber = int(value)\nprint(number)\n`,
    fixedCode: `value = "abc"\ntry:\n    number = int(value)\nexcept ValueError:\n    number = 0\nprint(number)\n`,
  },
  {
    id: 'fix_python_sort_none_comparison',
    problem: 'Sorting a list containing None alongside numbers raises TypeError in Python 3',
    errorType: 'TypeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `records = [{"score": 5}, {"score": None}, {"score": 3}]\nvalues = [r.get("score") for r in records]\nvalues.sort()\nprint(values)\n`,
    fixedCode: `records = [{"score": 5}, {"score": None}, {"score": 3}]\nvalues = [r.get("score", 0) or 0 for r in records]\nvalues.sort()\nprint(values)\n`,
  },
  {
    id: 'fix_python_unhandled_stop_iteration',
    problem: 'Calling next() on an exhausted iterator without a default raises StopIteration',
    errorType: 'StopIteration',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `def first_positive(numbers):\n    it = iter(numbers)\n    while True:\n        value = next(it)\n        if value > 0:\n            return value\n\nprint(first_positive([-1, -2, -3]))\n`,
    fixedCode: `def first_positive(numbers):\n    it = iter(numbers)\n    while True:\n        value = next(it, None)\n        if value is None:\n            return None\n        if value > 0:\n            return value\n\nprint(first_positive([-1, -2, -3]))\n`,
  },
  {
    id: 'fix_python_sort_mixed_types',
    problem: 'Sorting a list with mixed str/int elements raises TypeError in Python 3',
    errorType: 'TypeError',
    category: 'python',
    environment: ENV,
    testCommand: TEST_COMMAND,
    fileExtension: EXT,
    brokenCode: `values = [3, "a", 2]\nprint(sorted(values))\n`,
    fixedCode: `values = [3, "a", 2]\nprint(sorted(values, key=str))\n`,
  },
];
